results_folder: /media/joebillingsley/Data/projects/NFV_PlacementModel_Journal/temp
num_evaluations: 12000
num_runs: 30
utilisation: 0.6
vms_per_server: 3

num_splits: 2
test_sizes: 0 #All

accuracy: 5.0
converged_iterations: 10
port_sr: 20.0
port_ql: 20.0
active_cost: 30.0
idle_cost: 10.0

pop_size: 120
pc: 0.9

mean_service_len: 5.0
variance_service_len: 1.0
min_service_len: 2.0
max_service_len: 12.0
mean_prod_rate: 10.0
variance_prod_rate: 3.0
min_prod_rate: 0.1
mean_service_rate: 10.0
variance_service_rate: 3.0
min_service_rate: 1.0
vnf_queue_length: 20