//
// Generated file, do not edit! Created by nedtool 5.5 from src/DestMessage.msg.
//

#ifndef __SIMULATION_DESTMESSAGE_M_H
#define __SIMULATION_DESTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace simulation {

/**
 * Class generated from <tt>src/DestMessage.msg:18</tt> by nedtool.
 * <pre>
 * message DestMessage
 * {
 *     int srcServer;
 *     bool isExternalMessage;
 * 
 *     int destination;
 * 
 *     int position = 0;	// Which VNF in the service the message is up to
 *     int hopCount = 0;	// Number of switches/VNFs visited
 *     int serviceId = 0;	// The ID of the service the message belongs too
 * 
 *     bool visitedSDN = false;
 *     bool hasFinished = false;
 * 
 *     simtime_t produced;
 *     simtime_t queued;
 * }
 * </pre>
 */
class DestMessage : public ::omnetpp::cMessage
{
  protected:
    int srcServer;
    bool isExternalMessage;
    int destination;
    int position;
    int hopCount;
    int serviceId;
    bool visitedSDN;
    bool hasFinished;
    ::omnetpp::simtime_t produced;
    ::omnetpp::simtime_t queued;

  private:
    void copy(const DestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DestMessage&);

  public:
    DestMessage(const char *name=nullptr, short kind=0);
    DestMessage(const DestMessage& other);
    virtual ~DestMessage();
    DestMessage& operator=(const DestMessage& other);
    virtual DestMessage *dup() const override {return new DestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcServer() const;
    virtual void setSrcServer(int srcServer);
    virtual bool getIsExternalMessage() const;
    virtual void setIsExternalMessage(bool isExternalMessage);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getPosition() const;
    virtual void setPosition(int position);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getServiceId() const;
    virtual void setServiceId(int serviceId);
    virtual bool getVisitedSDN() const;
    virtual void setVisitedSDN(bool visitedSDN);
    virtual bool getHasFinished() const;
    virtual void setHasFinished(bool hasFinished);
    virtual ::omnetpp::simtime_t getProduced() const;
    virtual void setProduced(::omnetpp::simtime_t produced);
    virtual ::omnetpp::simtime_t getQueued() const;
    virtual void setQueued(::omnetpp::simtime_t queued);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DestMessage& obj) {obj.parsimUnpack(b);}

} // namespace simulation

#endif // ifndef __SIMULATION_DESTMESSAGE_M_H

